name: peanut
version: 6.0.1-wip
description: >-
  Update your GitHub gh-pages branch with the compiled output of your Dart web
  app. Supports 'pub build' and the new 'pub run build_runner'.
repository: https://github.com/kevmoo/peanut.dart
environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.6.0
  build_cli_annotations: ^2.1.1
  checked_yaml: ^2.0.1
  git: ^2.2.1
  glob: ^2.0.0
  io: ^1.0.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  stack_trace: ^1.12.1
  yaml: ^3.1.2

dev_dependencies:
  build_cli: ^2.2.8
  build_runner: ^2.8.0
  build_verify: ^3.1.0
  build_version: ^2.1.3

  # build_web_compilers is here to support the `example` dir
  build_web_compilers: ^4.2.3

  dart_flutter_team_lints: ^3.0.0
  json_serializable: ^6.11.1
  # Needed because we are configuring `combining_builder`
  source_gen: ^4.0.1
  test: ^1.26.3
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

  # For the `example` dir
  web: ^1.1.1

executables:
  peanut: peanut
