name: peanut
version: 1.1.5-dev
description: >-
  Update your GitHub gh-pages branch with the compiled output of your Dart web
  app. Supports 'pub build' and the new 'pub run build_runner'.
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/peanut.dart
environment:
  sdk: '>=2.0.0-dev.22 <2.0.0'

dependencies:
  args: '>=0.13.0 <2.0.0'
  build_cli_annotations: ^0.1.0
  git: ^0.5.1
  glob: ^1.1.5
  io: ^0.3.2+1
  path: ^1.3.4

dev_dependencies:
  build_cli: ^0.1.0
  build_runner: '>=0.7.10 <0.9.0'
  build_web_compilers: ^0.3.0
  test: ^0.12.0
  test_process: ^1.0.1

executables:
  peanut: peanut
